/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CuaHangRouteImport } from './routes/cua-hang'
import { Route as GioHangRouteImport } from './routes/gio-hang'
import { Route as GioTraiCayRouteImport } from './routes/gio-trai-cay'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as QuanLyRouteImport } from './routes/quan-ly'
import { Route as ThanhToanRouteImport } from './routes/thanh-toan'
import { Route as TrapCuoiHoiRouteImport } from './routes/trap-cuoi-hoi'
import { Route as SanPhamIdRouteImport } from './routes/san-pham.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuaHangRoute = CuaHangRouteImport.update({
  id: '/cua-hang',
  path: '/cua-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const GioHangRoute = GioHangRouteImport.update({
  id: '/gio-hang',
  path: '/gio-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const GioTraiCayRoute = GioTraiCayRouteImport.update({
  id: '/gio-trai-cay',
  path: '/gio-trai-cay',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyRoute = QuanLyRouteImport.update({
  id: '/quan-ly',
  path: '/quan-ly',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanhToanRoute = ThanhToanRouteImport.update({
  id: '/thanh-toan',
  path: '/thanh-toan',
  getParentRoute: () => rootRouteImport,
} as any)
const TrapCuoiHoiRoute = TrapCuoiHoiRouteImport.update({
  id: '/trap-cuoi-hoi',
  path: '/trap-cuoi-hoi',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamIdRoute = SanPhamIdRouteImport.update({
  id: '/san-pham/$id',
  path: '/san-pham/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cua-hang': typeof CuaHangRoute
  '/gio-hang': typeof GioHangRoute
  '/gio-trai-cay': typeof GioTraiCayRoute
  '/lien-he': typeof LienHeRoute
  '/quan-ly': typeof QuanLyRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/trap-cuoi-hoi': typeof TrapCuoiHoiRoute
  '/san-pham/$id': typeof SanPhamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cua-hang': typeof CuaHangRoute
  '/gio-hang': typeof GioHangRoute
  '/gio-trai-cay': typeof GioTraiCayRoute
  '/lien-he': typeof LienHeRoute
  '/quan-ly': typeof QuanLyRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/trap-cuoi-hoi': typeof TrapCuoiHoiRoute
  '/san-pham/$id': typeof SanPhamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cua-hang': typeof CuaHangRoute
  '/gio-hang': typeof GioHangRoute
  '/gio-trai-cay': typeof GioTraiCayRoute
  '/lien-he': typeof LienHeRoute
  '/quan-ly': typeof QuanLyRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/trap-cuoi-hoi': typeof TrapCuoiHoiRoute
  '/san-pham/$id': typeof SanPhamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cua-hang'
    | '/gio-hang'
    | '/gio-trai-cay'
    | '/lien-he'
    | '/quan-ly'
    | '/thanh-toan'
    | '/trap-cuoi-hoi'
    | '/san-pham/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cua-hang'
    | '/gio-hang'
    | '/gio-trai-cay'
    | '/lien-he'
    | '/quan-ly'
    | '/thanh-toan'
    | '/trap-cuoi-hoi'
    | '/san-pham/$id'
  id:
    | '__root__'
    | '/'
    | '/cua-hang'
    | '/gio-hang'
    | '/gio-trai-cay'
    | '/lien-he'
    | '/quan-ly'
    | '/thanh-toan'
    | '/trap-cuoi-hoi'
    | '/san-pham/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuaHangRoute: typeof CuaHangRoute
  GioHangRoute: typeof GioHangRoute
  GioTraiCayRoute: typeof GioTraiCayRoute
  LienHeRoute: typeof LienHeRoute
  QuanLyRoute: typeof QuanLyRoute
  ThanhToanRoute: typeof ThanhToanRoute
  TrapCuoiHoiRoute: typeof TrapCuoiHoiRoute
  SanPhamIdRoute: typeof SanPhamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cua-hang': {
      id: '/cua-hang'
      path: '/cua-hang'
      fullPath: '/cua-hang'
      preLoaderRoute: typeof CuaHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gio-hang': {
      id: '/gio-hang'
      path: '/gio-hang'
      fullPath: '/gio-hang'
      preLoaderRoute: typeof GioHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gio-trai-cay': {
      id: '/gio-trai-cay'
      path: '/gio-trai-cay'
      fullPath: '/gio-trai-cay'
      preLoaderRoute: typeof GioTraiCayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly': {
      id: '/quan-ly'
      path: '/quan-ly'
      fullPath: '/quan-ly'
      preLoaderRoute: typeof QuanLyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanh-toan': {
      id: '/thanh-toan'
      path: '/thanh-toan'
      fullPath: '/thanh-toan'
      preLoaderRoute: typeof ThanhToanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trap-cuoi-hoi': {
      id: '/trap-cuoi-hoi'
      path: '/trap-cuoi-hoi'
      fullPath: '/trap-cuoi-hoi'
      preLoaderRoute: typeof TrapCuoiHoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$id': {
      id: '/san-pham/$id'
      path: '/san-pham/$id'
      fullPath: '/san-pham/$id'
      preLoaderRoute: typeof SanPhamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuaHangRoute: CuaHangRoute,
  GioHangRoute: GioHangRoute,
  GioTraiCayRoute: GioTraiCayRoute,
  LienHeRoute: LienHeRoute,
  QuanLyRoute: QuanLyRoute,
  ThanhToanRoute: ThanhToanRoute,
  TrapCuoiHoiRoute: TrapCuoiHoiRoute,
  SanPhamIdRoute: SanPhamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
